common:
    lid_topic:  "/ml_/pointcloud"
    imu_topic:  "/imu/data"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
    scan_line: 56
    scan_rate: 20                # only need to be set for velodyne, unit: Hz,
    blind: 0.1
    point_filter_num: 1

mapping:
    down_sample_size: 0.4
    max_iteration: 4
    voxel_size: 1.0
    max_layer: 4                # 4 layer, 0, 1, 2, 3
    layer_point_size: [ 5, 5, 5, 5, 5 ]
    plannar_threshold: 0.01
    max_points_size: 1000
    max_cov_points_size: 1000

    fov_degree:    360.0
    det_range:     500.0    
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [0.0352416, -0.000342095,   -0.0103698]
    extrinsic_R: [0.9999154, -0.0015532,  0.0129151, 
                  0.0013864,  0.9999157,  0.0129140, 
                 -0.0129340, -0.0128950,  0.9998332]

noise_model:
    ranging_cov: 0.04
    angle_cov: 0.1
    acc_cov: 0.2
    gyr_cov: 0.05
    b_acc_cov: 0.0043
    b_gyr_cov: 0.000266


publish:
    pub_voxel_map: false
    publish_max_voxel_layer: 1         # only publish 0,1,2 layer's plane
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file;
    # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
